import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Providers } from "@/components/Provider";
import { SideNavigation } from "@/components/SideNavigation";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex`} id={"__next"}>
        <Providers>
          <div id={"__modal"}></div>
          <SideNavigation />
          {children}
        </Providers>
      </body>
    </html>
  );
}
